### ISSUE TITLE
Panic when trying to load profile

### ISSUE THREAD

**Issue by icewind1991** [nokia/memory-profiler#13]
When trying to open a generated profile, the cli panics with an "Address already in use" error.

Both the profiler library and the cli have been build from a fresh checkout from less then an hour old using today's rust nightly.

The profile causing the issue is attached below

[memory-profiling_parse_demo_1558712158_50705.dat.gz](https://github.com/nokia/memory-profiler/files/3217642/memory-profiling_parse_demo_1558712158_50705.dat.gz)

**Comment by koute** [comment]
By default the CLI uses port 8080; the error message means that you already have something open on that port.

Set a different port with `--port` and try again.

**Comment by icewind1991** [comment]
Right, I should have been able to figure that one out myself :see_no_evil: 

Sorry for the noise
