### ISSUE TITLE
Build memory-profiler-cli failed

### ISSUE THREAD

**Issue by aguludunu** [nokia/memory-profiler#16]
1. My environment is Ubuntu 18.04
2. Yarn has been installed already
3. Rust has been changed to nightly version
4. I run "cargo build --release -p memory-profiler" suceessfully and libmemory_profiler.so has been generate already

When I run "cargo build --release -p memory-profiler-cli", it failed and the error log as below:

davidwang@system-MS-7918:~/Tools/memory-profiler$ cargo build --release -p memory-profiler-cli
   Compiling server-core v0.1.0 (/home/davidwang/Tools/memory-profiler/server-core)
00h00m00s 0/0: : **error: failed to run custom build command for `server-core v0.1.0** (/home/davidwang/Tools/memory-profiler/server-core)`

Caused by:
  process didn't exit successfully: `/home/davidwang/Tools/memory-profiler/target/release/build/server-core-5dfb1577abf53aa3/build-script-build` (exit code: 101)
--- stderr
**ERROR: [Errno 2] No such file or directory: 'install'**
thread 'main' panicked at 'Failed to install the dependencies for the WebUI; child process exited with error code Some(1)! You might want to try to run 'rm -Rf ~/.cache/yarn' and try again.', server-core/build.rs:61:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: semalock::Semalock::with
             at server-core/build.rs:61
             at /home/davidwang/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:99
             at /rustc/8869ee03d7f258e1b76a11c6fbb01b5708a9f504/src/libcore/result.rs:639
             at /home/davidwang/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:96
   8: build_script_build::main
             at server-core/build.rs:46
   9: std::rt::lang_start::{{closure}}
             at /rustc/8869ee03d7f258e1b76a11c6fbb01b5708a9f504/src/libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  12: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  13: main
  14: __libc_start_main
  15: _start

It seems to find install dir failed, but where should the dir be?

**Comment by koute** [comment]
Which version of Yarn do you have installed?

Can you manually go into the `webui` directory and manually run `yarn install` and see what happens?

Also, can you try deleting `node_modules` inside of `webui` and `.cache/yarn` in your home directory?

**Comment by aguludunu** [comment]
Which version of Yarn do you have installed?
==> My yarn version is 0.32

Can you manually go into the webui directory and manually run yarn install and see what happens?
==>00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Also, can you try deleting node_modules inside of webui and .cache/yarn in your home directory?
==>The tow dirs  are not exist at all.

**Comment by koute** [comment]
Your Yarn is most likely too old; can you try with a more recent version?

**Comment by aguludunu** [comment]
Hi koute, my problem has resolved with your help, thank you very much!

I have updated my yarn from 0.32 to 1.16 and the problem is resolved.

1. curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
2. echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
3. sudo apt-get update
4. sudo apt-get install yarn

**Comment by treeshateorcs** [comment]
i'm having a similar issue

```
  Compiling actix-rt v0.2.5
   Compiling serde_json v1.0.41
   Compiling serde_urlencoded v0.6.1
   Compiling actix-router v0.1.5
   Compiling serde_urlencoded v0.5.5
   Compiling trust-dns-resolver v0.11.1
   Compiling ahash v0.2.16
   Compiling server-core v0.5.0 (/home/tho/src/memory-profiler/server-core)
error: failed to run custom build command for `server-core v0.5.0 (/home/tho/src/memory-profiler/server-core)`

Caused by:
  process didn't exit successfully: `/home/tho/.cargo/lib/release/build/server-core-888d66a46965f391/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'failed to acquire a semaphore: "OpenOptions::open failed: entity not found"', server-core/build.rs:43:64
  stack backtrace:
     0:     0x560dedc70297 - <unknown>
     1:     0x560dedc8b81c - <unknown>
     2:     0x560dedc6d9c2 - <unknown>
     3:     0x560dedc72415 - <unknown>
     4:     0x560dedc71f6a - <unknown>
     5:     0x560dedc72bb1 - <unknown>
     6:     0x560dedc726f7 - <unknown>
     7:     0x560dedc7075c - <unknown>
     8:     0x560dedc72659 - <unknown>
     9:     0x560dedc8abf1 - <unknown>
    10:     0x560dedc8aa13 - <unknown>
    11:     0x560dedc51890 - <unknown>
    12:     0x560dedc50eeb - <unknown>
    13:     0x560dedc51c18 - <unknown>
    14:     0x560dedc72fd7 - <unknown>
    15:     0x560dedc51c0d - <unknown>
    16:     0x7fdf94cde152 - __libc_start_main
    17:     0x560dedc500ae - <unknown>
    18:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

archlinux. everything is latest and rust nightly
