### ISSUE TITLE
memory-profiler-cli: failed to fill whole buffer

### ISSUE THREAD

**Issue by dominikbraun** [nokia/memory-profiler#19]
This error occurs on Ubuntu 18.04.2 LTS.

After profiling my application with

```
LD_PRELOAD=./libmemory_profiler.so ./haystack --haystack .. --needle test -e -b
```

and starting the server with

```
./memory-profiler-cli server memory-profiling_haystack_1561391660_18942.dat
```

the following error appears:

```
ERROR memory_profiler_cli failed to fill whole buffer
```

Any ideas on that issue? :)

**Comment by koute** [comment]
Unfortunately that doesn't tell me too much.

Could you perhaps send me the data file? (Either attach it here or send it to my email?) Just remember that the data file has your executable embedded into it, in case you aren't allowed to share it.

**Comment by mirfatif** [comment]
For me it was happening because I had set the `MEMORY_PROFILER_OUTPUT` and `LD_PRELOAD` variables. So the  `bytehound server` process itself was being profiled which overwrote the output file.
