### ISSUE TITLE
Idea: Generate memory flamegraph with inferno

### ISSUE THREAD

**Issue by pothos** [nokia/memory-profiler#20]
Hello,
maybe the most things for this are already in place and it's easy to do.
Currently manual usage of the heaptrack GUI is needed to see the memory flamegraph. [Inferno](https://github.com/jonhoo/inferno) could be used to directly generate an interactive SVG by exporting a perf-compatible text format (the text format can even be without collapsed stacks, as there is the `inferno-collapse-perf` command for that).

**Comment by koute** [comment]
The profiler already uses `inferno` and can already generate flamegraphs. (: You just need to use the `server` subcommand to be able to access that functionality. (You can either access it through the GUI, or through the REST API.)

**Comment by pothos** [comment]
Yes, I saw them for leaked allocations but did not realize that I could change `/data/…/export/flamegraph/flame.svg?lifetime=only_leaked` to `/data/…/export/flamegraph/flame.svg`. So it's just a matter of having a link in the UI?

**Comment by koute** [comment]
> So it's just a matter of having a link in the UI?

There is a link in the UI. (: When you browse through the allocations you can click in the upper right corner to access a menu with a link to a flamegraph. (I might replace that menu with a sidebar in the future so that it's more obvious.)

**Comment by pothos** [comment]
Ah :) Yes, similar to the leaked-allocation flamegraph link such a link could be displayed behind `All allocations` as well. Anyway, thanks for the reply.
